### ISSUE TITLE
Join/Leave Not Updating

### ISSUE THREAD

**Issue by jpleasants** [Insax/palworld-admin-tool#7]
My view stopped updating shortly after starting unless I executed `php artisan short-schedule:run &`

Manual browser refresh also showed no new updates

**Comment by jpleasants** [comment]
Confirmed by restarting the container and leaving/re-joining Palworld server. View did not update that player was online and log did not update with join/leave messages. Waited a couple minutes to confirm.

Ran `php artisan short-schedule:run &` and view immediately began updating

**Comment by Insax** [comment]
Needs a rebuild of the docker image

Appearantly due to the argument `--lifetime=60` which is configured for the container on the scheduler, it stops after some restarts.

Either needs infinite restarts or removal of the lifetime

**Comment by Insax** [comment]
Fixed with the newest update of the docker container
